[[ menu.main ]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -99

[[ menu.main ]]
  identifier = "about-me"
  name = "About Me"
  url = "/about-me"
  weight = -10

[[ menu.main ]]
  identifier = "linkedin"
  name = "/in/{{ .Env.LINKEDIN_HANDLE }}"
  pre = "<img src=/icons/linkedin.png height=16px weight=16px>"
  url = "https://linkedin.com/in/{{ .Env.LINKEDIN_HANDLE }}"
  weight = -7

[[ menu.main ]]
  identifier = "twitter"
  name = "@easiestnameever"
  pre = "<img src=/icons/twitter.png height=16px weight=16px>"
  url = "https://twitter.com/@{{ .Env.TWITTER_HANDLE }}"
  weight = -6

[[ menu.main ]]
  identifier = "github"
  name = "GitHub"
  pre = "<img src=/icons/twitter.png height=16px weight=16px>"
  url = "https://github.com/{{ .Env.GITHUB_HANDLE }}"
  weight = -5
